authentification/urls.py
from django.urls import path
from .views import login


app_name = 'authentification'
urlpatterns = [
    path('', login, name= 'login'),
]

dashboard/urls.py
from django.urls import path
from .views import dashboard

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name= 'index'),
]

eleve/urls.py
from django.urls import path
from .views import *

app_name = 'eleve'

urlpatterns = [
    path('', eleve, name='index'),
    path('ajout_eleve', ajout_eleve, name='ajout_eleve'),
    path('modifier_eleve', modifier_eleve, name='modifier_eleve'),
]

professeur/urls.py
from django.urls import path
from .views import *

app_name = 'professeur'

urlpatterns = [
    path('', professeur, name= 'index'),
    path('ajout_professeur', ajout_prof, name= 'ajout_prof'),
    path('modifier_professeur', modifier_prof, name= 'modifier_prof'),
]

rapport/urls.py
from django.urls import path
from .views import rapport

app_name = 'rapport'

urlpatterns = [
    path('', rapport, name= 'index'),
]

utilisateur/urls.py
from django.urls import path
from .views import *

app_name = 'utilisateur'

urlpatterns = [
    path('', utilisateur, name= 'index'),
    path('add-user-page', ajout_utilisateur, name= 'ajout_utilisateur'),
    path('update-user-page', modifier_utilisateur, name= 'modifier_utilisateur'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
# from eleve.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentification.urls'), ),
    path('eleve/', include('eleve.urls'), ),
    path('dashboard/', include('dashboard.urls'), ),
    path('professeur/', include('professeur.urls'), ),
    path('utilisateur/', include('utilisateur.urls'), ),
    path('rapport/', include('rapport.urls'), ),
]

authentification/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

eleve/models.py
from django.db import models

# Create your models here.

professeur/models.py
from django.db import models

# Create your models here.

rapport/models.py
from django.db import models

# Create your models here.

utilisateur/models.py
from django.db import models

# Create your models here.

authentification/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def login(request):
    return render(request, 'authentification/index.html')

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def dashboard(request):
    return render(request, 'dashboard/index.html')

eleve/views.py
from django.shortcuts import render 
from django.http import HttpResponse

# Create your views here.

def eleve(request):
    return render(request, "eleve/eleve.html")

def ajout_eleve(request):
    return render(request, "eleve/ajout_eleve.html")

def modifier_eleve(request):
    return render(request, "eleve/modifier_eleve.html")

def show(request):
    context = {
        'title': 'The blaclist',
        'Article' : 'abrabrakatabra'
    }

professeur/views.py
from django.shortcuts import render 
from django.http import HttpResponse

# Create your views here.

def professeur(request):
    return render(request, "professeur/professeur.html")

def ajout_prof(request):
    return render(request, "professeur/ajout_prof.html")

def modifier_prof(request):
    return render(request, "professeur/modifier_prof.html")

def show(request):
    context = {
        'title': 'The blaclist',
        'Article' : 'abrabrakatabra'
    }

rapport/views.py
from django.shortcuts import render 
from django.http import HttpResponse

# Create your views here.

def rapport(request):
    return render(request, "rapport/rapport.html")

def show(request):
    context = {
        'title': 'The blaclist',
        'Article' : 'abrabrakatabra'
    }

utilisateur/views.py
from django.shortcuts import render 
from django.http import HttpResponse

# Create your views here.

def utilisateur(request):
    return render(request, "utilisateur/utilisateur.html")

def ajout_utilisateur(request):
    return render(request, "utilisateur/ajout_utilisateur.html")

def modifier_utilisateur(request):
    return render(request, "utilisateur/modifier_utilisateur.html")

def show(request):
    context = {
        'title': 'The blaclist',
        'Article' : 'abrabrakatabra'
    }

authentification/templates/authentification/index.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon Etab - Connexion</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body style="background-color: #555;">
    <div class="container">
        <div class="login-box">
            <div class="logo">
                <img src="{% static 'images/logo.png' %}" alt="Logo" />
                <h1>Mon Etab</h1>
            </div>
            <form method="" action="{% url 'dashboard:index' %}">
                <div class="input-group">
                    <label for="username">Identifiant</label>
                    <input type="text" id="username" name="username" required>
                </div>
                <div class="input-group">
                    <label for="password">Mot de passe</label>
                    <input type="password" id="password" name="password" required>
                </div>
                <button type="submit" class="login-btn">Connexion</button>
            </form>
        </div>
    </div>
</body>

</html>

dashboard/templates/dashboard/index.html
{%  load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tableau de bord</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar">
        <h2>Mon Etab</h2>
        <hr>
        <ul>
            <li class="active">
                <a href="{% url 'dashboard:index' %}"><i class="fas fa-tachometer-alt"></i> Tableau de bord</a>
            </li>
            <li>
                <a href="{% url 'eleve:index' %}"><i class="fas fa-user-graduate"></i> Élèves</a>
            </li>
            <li>
                <a href="{% url 'professeur:index' %}"><i class="fas fa-chalkboard-teacher"></i> Professeurs</a>
            </li>
            <li>
                <a href="{% url 'utilisateur:index' %}"><i class="fas fa-chart-line"></i> utilisateurs</a>
            </li>
            <li>
                <a href="{% url 'rapport:index' %}"><i class="fas fa-chart-line"></i> Rapport</a>
            </li>
        </ul>
        <hr style="margin-top:270px;">
        <ul>
            <li>
                <a href="index.html"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
            </li>
        </ul>
    </div>
    <div class="content">
        <div class="back-button" style="justify-content: flex-start;" >
            <h1 style="color:black;">Tableau de bord</h1>
        </div>
        <div class="card-container">
            <div class="card">Nombre d'élèves<br>128 100</div>
            <div class="card">Nombre de professeurs<br>128 100</div>
            <div class="card">Nombre d'utilisateurs<br>128 100</div>
            <div class="card">
                <canvas id="pie-chart"></canvas>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

eleve/templates/eleve/ajout_eleve.html
{% extends 'base.html' %}

{% block title %}Tableau de bord{% endblock %}

{% block eleve_active %}active{% endblock %}

{% block content %}

    <div class="content">
        <div class="back-button" style="justify-content: flex-end;" >
            <a href="{% url 'eleve:index' %}"><i class="fas fa-arrow-left"></i> Retour</a>
        </div>

        <div class="form-container">
            <h1>Ajouter un élève</h1>

            <div class="form-group">
                <label for="nom">Nom</label>
                <input type="text" id="nom" name="nom">
            </div>

            <div class="form-group">
                <label for="prenom">Prénom</label>
                <input type="text" id="prenom" name="prenom">
            </div>

            <div class="form-group gender">
                <label>Sexe</label>
                <div>
                    <input type="radio" id="homme" name="sexe" value="homme">
                    <label for="homme">Homme</label>
                </div>
                <div>
                    <input type="radio" id="femme" name="sexe" value="femme">
                    <label for="femme">Femme</label>
                </div>
            </div>

            <div class="form-group">
                <label for="matricule">Matricule</label>
                <input type="text" id="matricule" name="matricule">
            </div>

            <div class="form-group">
                <label for="dateNaissance">Date de naissance</label>
                <input type="date" id="dateNaissance" name="dateNaissance">
            </div>

            <div class="form-group">
                <label for="classe">Sélectionner une classe</label>
                <select id="classe" name="classe">
                    <option value="6eme">6ème</option>
                    <option value="5eme">5ème</option>
                    <option value="4eme">4ème</option>
                    <option value="3eme">3ème</option>
                    <option value="2nde">2nde</option>
                    <option value="1ere">1ère</option>
                    <option value="terminale">Terminale</option>
                </select>
            </div>

            <div class="form-group">
                <label for="telephone">Téléphone</label>
                <input type="text" id="telephone" name="telephone">
            </div>

            <div class="form-group">
                <label for="ville">Ville</label>
                <input type="text" id="ville" name="ville">
            </div>

            <div class="form-actions">
                <button class="btn-cancel" onclick="confirmCancel()">Annuler</button>
                <button class="btn-save">Enregistrer</button>
            </div>
        </div>
    </div>
{% endblock %}

eleve/templates/eleve/eleve.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Tableau de bord{% endblock %}

{% block eleve_active %}active{% endblock %}

{% block content %}

    <div class="content1">
        <div class="back-button">
            <h1 style="color:black;">Liste des élèves</h1>
            <a href="{% url 'eleve:ajout_eleve' %}"><i class="fas fa-arrow-left"></i>Nouveau élève</a>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Genre</th>
                    <th>Classe</th>
                    <th>Matricule</th>
                    <th>Age</th>
                    <th>Téléphone</th>
                    <th>Ville</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>NDOFI</td>
                    <td>George</td>
                    <td>Homme</td>
                    <td>Te</td>
                    <td>030708000</td>
                    <td>25</td>
                    <td>0784545498</td>
                    <td>Abidjan</td>
                    <td>
                        <a href="{% url 'eleve:modifier_eleve' %}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                        <button style="background-color: rgb(212, 21, 21);">Supprimer</button>
                    </td>
                </tr>
                <tr>
                    <td>NONE</td>
                    <td>Suli</td>
                    <td>Femme</td>
                    <td>2nd</td>
                    <td>030708000</td>
                    <td>22</td>
                    <td>0224545498</td>
                    <td>Abidjan</td>
                    <td>
                        <a href="{% url 'eleve:modifier_eleve' %}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                        <button style="background-color: rgb(212, 21, 21);">Supprimer</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    {% endblock %}



{% block extra_js %}
<script src="{% static 'js/script.js' %}"></script>
{% block confirmation_js %}
<script src="{% static 'js/supprimer.js' %}"></script>
{% endblock %}
{% endblock %}

eleve/templates/eleve/modifier_eleve.html
{% extends 'base.html' %}

{% block title %}Tableau de bord{% endblock %}

{% block eleve_active %}active{% endblock %}

{% block content %}

    <div class="content">
        <div class="back-button" style="justify-content: flex-end;" >
            <a href="{% url 'eleve:index' %}"><i class="fas fa-arrow-left"></i> Retour</a>
        </div>

        <div class="form-container">
            <h1>Modifier un élève</h1>

            <div class="form-group">
                <label for="nom">Nom</label>
                <input type="text" id="nom" name="nom">
            </div>

            <div class="form-group">
                <label for="prenom">Prénom</label>
                <input type="text" id="prenom" name="prenom">
            </div>

            <div class="form-group gender">
                <label>Sexe</label>
                <div>
                    <input type="radio" id="homme" name="sexe" value="homme">
                    <label for="homme">Homme</label>
                </div>
                <div>
                    <input type="radio" id="femme" name="sexe" value="femme">
                    <label for="femme">Femme</label>
                </div>
            </div>

            <div class="form-group">
                <label for="matricule">Matricule</label>
                <input type="text" id="matricule" name="matricule">
            </div>

            <div class="form-group">
                <label for="dateNaissance">Date de naissance</label>
                <input type="date" id="dateNaissance" name="dateNaissance">
            </div>

            <div class="form-group">
                <label for="classe">Sélectionner une classe</label>
                <select id="classe" name="classe">
                    <option value="6eme">6ème</option>
                    <option value="5eme">5ème</option>
                    <option value="4eme">4ème</option>
                    <option value="3eme">3ème</option>
                    <option value="2nde">2nde</option>
                    <option value="1ere">1ère</option>
                    <option value="terminale">Terminale</option>
                </select>
            </div>

            <div class="form-group">
                <label for="telephone">Téléphone</label>
                <input type="text" id="telephone" name="telephone">
            </div>

            <div class="form-group">
                <label for="ville">Ville</label>
                <input type="text" id="ville" name="ville">
            </div>

            <div class="form-actions">
                <button class="btn-cancel" onclick="confirmCancel()">Annuler</button>
                <button class="btn-save">Enregistrer</button>
            </div>
        </div>
    </div>
{% endblock %}

professeur/templates/professeur/ajout_prof.html
{% extends 'base.html' %}

{% block title %}Liste des professeurs{% endblock %}

{% block professeur_active %}active{% endblock %}

{% block content %}

    <div class="content">
        <div class="back-button" style="justify-content: flex-end;" >
            <a href="{% url 'professeur:index' %}"><i class="fas fa-arrow-left"></i> Retour</a>
        </div>

        <div class="form-container">
            <h1>Ajouter un professeur</h1>

            <div class="form-group">
                <label for="nom">Nom</label>
                <input type="text" id="nom" name="nom">
            </div>

            <div class="form-group">
                <label for="prenom">Prénom</label>
                <input type="text" id="prenom" name="prenom">
            </div>

            <div class="form-group gender">
                <label>Sexe</label>
                <div>
                    <input type="radio" id="homme" name="sexe" value="homme">
                    <label for="homme">Homme</label>
                </div>
                <div>
                    <input type="radio" id="femme" name="sexe" value="femme">
                    <label for="femme">Femme</label>
                </div>
            </div>

            <div class="form-group">
                <label for="dateNaissance">Date de naissance</label>
                <input type="date" id="dateNaissance" name="dateNaissance">
            </div>

            <div class="form-group">
                <label for="classe">Sélectionner une Matière</label>
                <select id="classe" name="classe">
                    <option value="6eme">MAth</option>
                    <option value="5eme">Physique</option>
                    <option value="4eme">SVT</option>
                    <option value="3eme">Français</option>
                    <option value="2nde">HG</option>
                    <option value="1ere">EPS</option>
                    <option value="terminale">Anglais</option>
                </select>
            </div>

            <div class="form-group">
                <label for="telephone">Téléphone</label>
                <input type="text" id="telephone" name="telephone">
            </div>

            <div class="form-group">
                <label for="ville">Ville</label>
                <input type="text" id="ville" name="ville">
            </div>

            <div class="form-actions">
                <button class="btn-cancel" onclick="confirmCancel()">Annuler</button>
                <button class="btn-save">Enregistrer</button>
            </div>
        </div>
    </div>
{% endblock %}

professeur/templates/professeur/modifier_prof.html
{% extends 'base.html' %}

{% block title %}Liste des professeurs{% endblock %}

{% block professeur_active %}active{% endblock %}

{% block content %}

    <div class="content">
        <div class="back-button" style="justify-content: flex-end;" >
            <a href="{% url 'professeur:index' %}"><i class="fas fa-arrow-left"></i> Retour</a>
        </div>

        <div class="form-container">
            <h1>Modifier un professeur</h1>

            <div class="form-group">
                <label for="nom">Nom</label>
                <input type="text" id="nom" name="nom">
            </div>

            <div class="form-group">
                <label for="prenom">Prénom</label>
                <input type="text" id="prenom" name="prenom">
            </div>

            <div class="form-group gender">
                <label>Sexe</label>
                <div>
                    <input type="radio" id="homme" name="sexe" value="homme">
                    <label for="homme">Homme</label>
                </div>
                <div>
                    <input type="radio" id="femme" name="sexe" value="femme">
                    <label for="femme">Femme</label>
                </div>
            </div>

            <div class="form-group">
                <label for="dateNaissance">Date de naissance</label>
                <input type="date" id="dateNaissance" name="dateNaissance">
            </div>

            <div class="form-group">
                <label for="classe">Sélectionner une Matière</label>
                <select id="classe" name="classe">
                    <option value="6eme">MAth</option>
                    <option value="5eme">Physique</option>
                    <option value="4eme">SVT</option>
                    <option value="3eme">Français</option>
                    <option value="2nde">HG</option>
                    <option value="1ere">EPS</option>
                    <option value="terminale">Anglais</option>
                </select>
            </div>

            <div class="form-group">
                <label for="telephone">Téléphone</label>
                <input type="text" id="telephone" name="telephone">
            </div>

            <div class="form-group">
                <label for="ville">Ville</label>
                <input type="text" id="ville" name="ville">
            </div>

            <div class="form-actions">
                <button class="btn-cancel" onclick="confirmCancel()">Annuler</button>
                <button class="btn-save">Enregistrer</button>
            </div>
        </div>
    </div>
{% endblock %}

professeur/templates/professeur/professeur.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Liste des professeurs{% endblock %}

{% block professeur_active %}active{% endblock %}

{% block content %}
    <div class="back-button">
        <h1 style="color:black;">Liste des professeurs</h1>
        <a href="{% url 'professeur:ajout_prof' %}"><i class="fas fa-arrow-left"></i> Nouveau professeur</a>
    </div>
    <table>
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Matière</th>
                <th>Vacant</th>
                <th>Age</th>
                <th>Téléphone</th>
                <th>Ville</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Kouakou</td>
                <td>George</td>
                <td>Math</td>
                <td>Oui</td>
                <td>35</td>
                <td>0784545498</td>
                <td>Abidjan</td>
                <td>
                    <a href="{% url 'professeur:modifier_prof' %}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                    <button style="background-color: rgb(212, 21, 21);">Supprimer</button>
                </td>
            </tr>
            <tr>
                <td>AttA</td>
                <td>Flora</td>
                <td>Physique</td>
                <td>030708000</td>
                <td>28</td>
                <td>0224545498</td>
                <td>Abidjan</td>
                <td>
                    <a href="{% url 'professeur:modifier_prof' %}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                    <button style="background-color: rgb(212, 21, 21);">Supprimer</button>
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/script.js' %}"></script>
    {% block confirmation_js %}
    <script src="{% static 'js/supprimer.js' %}"></script>
    {% endblock %}
{% endblock %}

rapport/templates/rapport/rapport.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Liste des professeurs{% endblock %}

{% block rapport_active %}active{% endblock %}

{% block content %}
    <div class="content">
       

        <div class="form-container">
            <h1>Impresion Rapport</h1>

            <div class="form-group">
                <label for="classe">Sélectionner une classe</label>
                <select id="classe" name="classe">
                    <option value="6eme">6ème</option>
                    <option value="5eme">5ème</option>
                    <option value="4eme">4ème</option>
                    <option value="3eme">3ème</option>
                    <option value="2nde">2nde</option>
                    <option value="1ere">1ère</option>
                    <option value="terminale">Terminale</option>
                </select>
            </div>

            <div class="form-actions">
                <button class="btn-cancel" onclick="confirmCancel()">Générer format PDF</button>
                <button class="btn-save">Générer format Excel</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/script.js' %}"></script>
    {% block confirmation_js %}
    <script src="{% static 'js/supprimer.js' %}"></script>
    {% endblock %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mon Etab{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar">
        <h2>Mon Etab</h2>
        <hr>
        <ul>
            <li class="{% block dashboard_active %}{% endblock %}">
                <a href="{% url 'dashboard:index' %}"><i class="fas fa-tachometer-alt"></i> Tableau de bord</a>
            </li>
            <li class="{% block eleve_active %}{% endblock %}">
                <a href="{% url 'eleve:index' %}"><i class="fas fa-user-graduate"></i> Élèves</a>
            </li>
            <li>
                <a href="{% url 'professeur:index' %}"><i class="fas fa-chalkboard-teacher"></i> Professeurs</a>
            </li>
            <li>
                <a href="{% url 'utilisateur:index' %}"><i class="fas fa-chart-line"></i> utilisateurs</a>
            </li>
            <li>
                <a href="{% url 'rapport:index' %}"><i class="fas fa-chart-line"></i> Rapport</a>
            </li>
        </ul>
        <hr style="margin-top:270px;">
        <ul>
            <li>
                <a href="{% url 'authentification:login' %}"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
            </li>
        </ul>
    </div>
    <div class="content1">
        {% block content %}{% endblock %}
    </div>
    {% block extra_js %}
    <script src="{% static 'js/script.js' %}"></script>
    {% block confirmation_js %}{% endblock %}
{% endblock %}


</body>
</html>

utilisateur/templates/utilisateur/ajout_utilisateur.html
{% extends 'base.html' %}

{% block title %}Liste des professeurs{% endblock %}

{% block utlisateur_active %}active{% endblock %}

{% block content %}

    <div class="content">
        <div class="back-button" style="justify-content: flex-end;" >
            <a href="{% url 'utilisateur:index' %}"><i class="fas fa-arrow-left"></i> Retour</a>
        </div>

        <div class="form-container">
            <h1>Ajouter d'un utilisateur</h1>

            <div class="form-group">
                <label for="nom">Pseudo</label>
                <input type="text" id="nom" name="nom">
            </div>

            <div class="form-group">
                <label for="prenom">Mot de passe</label>
                <input type="text" id="prenom" name="prenom">
            </div>

            <div class="form-group">
                <label for="matricule">Confirmez le mot de passe</label>
                <input type="text" id="matricule" name="matricule">
            </div>

            <div class="form-actions">
                <button class="btn-cancel" onclick="confirmCancel()">Annuler</button>
                <button class="btn-save">Enregistrer</button>
            </div>
        </div>
    </div>
{% endblock %}

utilisateur/templates/utilisateur/modifier_utilisateur.html
{% extends 'base.html' %}

{% block title %}Liste des professeurs{% endblock %}

{% block utilisateur_active %}active{% endblock %}

{% block content %}

    <div class="content">
        <div class="back-button" style="justify-content: flex-end;" >
            <a href="{% url 'utilisateur:index' %}"><i class="fas fa-arrow-left"></i> Retour</a>
        </div>

        <div class="form-container">
            <h1>Modifier d'un utilisateur</h1>

            <div class="form-group">
                <label for="nom">Pseudo</label>
                <input type="text" id="nom" name="nom">
            </div>

            <div class="form-group">
                <label for="prenom">Mot de passe</label>
                <input type="text" id="prenom" name="prenom">
            </div>

            <div class="form-group">
                <label for="matricule">Confirmez le mot de passe</label>
                <input type="text" id="matricule" name="matricule">
            </div>

            <div class="form-actions">
                <button class="btn-cancel" onclick="confirmCancel()">Annuler</button>
                <button class="btn-save">Enregistrer</button>
            </div>
        </div>
    </div>
{% endblock %}

utilisateur/templates/utilisateur/utilisateur.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Liste des utilisateurs{% endblock %}

{% block utilisateur_active %}active{% endblock %}

{% block content %}
    <div class="content1">
        <div class="back-button">
            <h1 style="color:black;">Liste des Utilisateurs</h1>
            <a href="{% url 'utilisateur:ajout_utilisateur' %}"><i class="fas fa-arrow-left"></i>Nouveau utilisateur</a>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Pseudo</th>
                    <th>Date de création</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Admin</td>
                    <td>16/08/2024</td>
                    <td>
                        <a href="{% url 'utilisateur:modifier_utilisateur' %}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                    </td>
                </tr>
                <tr>
                    <td>User2</td>
                    <td>16/08/2024</td>
                    <td>
                        <a href="{% url 'utilisateur:modifier_utilisateur' %}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/supprimer.js' %}"></script>
{% endblock %}